openapi: 3.0.1
info:
  title: TFT DB Service
  description: Teamfight tactics database service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
paths:
  '/riot/':
    get:
      summary: Make riot api request or use cached result 
      operationId: riotApi
      parameters:
        - name: riot_api_url
          in: query
          required: true
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: 400 Bad Request
          content: {}
        '500':
          description: 500 Internal Server Error
          content: {}
  '/{Server}/challenger':
    get:
      summary: Get Challenger League
      parameters:
        - name: Server
          in: path
          required: true
          schema:
            type: string
            enum:
              - EUW1
              - KR1
              - NA1
              - TR1
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: 400 Bad Request
          content: {}
        '500':
          description: 500 Internal Server Error
          content: {}
  '/{Server}/grandmaster':
    get:
      summary: Get Grandmaster League
      parameters:
        - name: Server
          in: path
          required: true
          schema:
            type: string
            enum:
              - EUW1
              - KR1
              - NA1
              - TR1
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: 400 Bad Request
          content: {}
        '500':
          description: 500 Internal Server Error
          content: {}
  '/{Server}/matchList':
    get:
      summary: Get Grandmaster League
      parameters:
        - name: Server
          in: path
          required: true
          schema:
            type: string
            enum:
              - EUW1
              - KR1
              - NA1
              - TR1
        - name: Player
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: 400 Bad Request
          content: {}
        '500':
          description: 500 Internal Server Error
          content: {}
