openapi: 3.0.1
info:
  description: Teamfight tactics database service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: TFT DB Service
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /
paths:
  /riot/:
    get:
      operationId: riotApi
      parameters:
      - explode: true
        in: query
        name: riot_api_url
        required: true
        schema:
          format: uri
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: 200 OK
        "400":
          content: {}
          description: 400 Bad Request
        "500":
          content: {}
          description: 500 Internal Server Error
      summary: Make riot api request or use cached result
  /{Server}/challenger:
    get:
      parameters:
      - explode: false
        in: path
        name: Server
        required: true
        schema:
          enum:
          - EUW1
          - KR1
          - NA1
          - TR1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: 200 OK
        "400":
          content: {}
          description: 400 Bad Request
        "500":
          content: {}
          description: 500 Internal Server Error
      summary: Get Challenger League
  /{Server}/grandmaster:
    get:
      parameters:
      - explode: false
        in: path
        name: Server
        required: true
        schema:
          enum:
          - EUW1
          - KR1
          - NA1
          - TR1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: 200 OK
        "400":
          content: {}
          description: 400 Bad Request
        "500":
          content: {}
          description: 500 Internal Server Error
      summary: Get Grandmaster League
  /{Server}/matchList:
    get:
      parameters:
      - explode: false
        in: path
        name: Server
        required: true
        schema:
          enum:
          - EUW1
          - KR1
          - NA1
          - TR1
          type: string
        style: simple
      - explode: true
        in: query
        name: Player
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: 200 OK
        "400":
          content: {}
          description: 400 Bad Request
        "500":
          content: {}
          description: 500 Internal Server Error
      summary: Get Grandmaster League
components:
  schemas: {}

